//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-KPC8BMG\\Nguyen Tuan Anh;Initial Catalog=QuanLyNhanSu;Integrat" +
            "ed Security=True")]
        public string QuanLyNhanSuConnectionString {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-KPC8BMG\\SQLEXPRESS;Initial Catalog=QuanLyNhanSu;Integrated Se" +
            "curity=True")]
        public string QuanLyNhanSuConnectionString1 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-3PM2V18\\SQLEXPRESS;Initial Catalog=QuanLyNhanSu;Integrated Se" +
            "curity=True")]
        public string QuanLyNhanSuConnectionString2 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-3PM2V18\\SQLEXPRESS;Initial Catalog=QuanLyNhanSu;Integrated Se" +
            "curity=True")]
        public string QuanLyNhanSuConnectionString21 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString21"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-DN7MI1FU\\SQLEXPRESS;Initial Catalog=QuanLyNhanSu;Integrated Se" +
            "curity=True")]
        public string QuanLyNhanSuConnectionString3 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B74R34B\\SQLEXPRESS;Initial Catalog=QuanLyNhanSu;Integrated Se" +
            "curity=True")]
        public string QuanLyNhanSuConnectionString4 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-FI1VAB7\\DT;Initial Catalog=QuanLyNhanSu;Integrated Security=T" +
            "rue")]
        public string QuanLyNhanSuConnectionString5 {
            get {
                return ((string)(this["QuanLyNhanSuConnectionString5"]));
            }
        }
    }
}
